defaultPortal: CodeSevenic
portals:
  - name: CodeSevenic
    portalId: 25522688
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CISo_fi2MBIJAA0AAAAA4A0DGIDklQwgzOzCDSju6QwyFPHcWT5yD3H9o7NWKRtbSfQOZV_rOjcAAARBAAAAeAAAAAAAAAAAAAAAAAAAAAQAAMAHAP7_MTwAAAYAAABgAAAAAAAAAAAAAAAAADACQhSoLlGfD0mlQajithDhRkUQXYDE_0oDZXUxUgBaAA
        expiresAt: '2022-09-24T10:51:07.655Z'
    personalAccessKey: >-
      CiRldTEtN2FjMi04ZjQ3LTQ0NjAtYjk2MS1iYzE1ZTdjNGNmYTYQgOSVDBjM7MINKhkABeaRgnT2uVni73e5gFnF2Cz9PMMRmA51SgNldTE
