defaultPortal: CodeSevenic
portals:
  - name: CodeSevenic
    portalId: 25522688
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CIeU2vi2MBIJAA0AAAAA4A0DGIDklQwgzOzCDSju6QwyFNbxF0BXuF3xEx3HGO0qGH0cZaH0OjcAAARBAAAAeAAAAAAAAAAAAAAAAAAAAAQAAMAHAP7_MTwAAAYAAABgAAAAAAAAAAAAAAAAADACQhQa42PYal7JaVN4IQ5nHXBKfm6tPEoDZXUxUgBaAA
        expiresAt: '2022-09-24T10:41:31.658Z'
    personalAccessKey: >-
      CiRldTEtN2FjMi04ZjQ3LTQ0NjAtYjk2MS1iYzE1ZTdjNGNmYTYQgOSVDBjM7MINKhkABeaRgnT2uVni73e5gFnF2Cz9PMMRmA51SgNldTE
