defaultPortal: CodeSevenic
portals:
  - name: CodeSevenic
    portalId: 25522688
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          COXnv_u2MBIJAA0AAAAA4A0DGIDklQwgzOzCDSju6QwyFMgW48IZ5CuU490K33SjFvb5dACTOjcAAARBAAAAeAAAAAAAAAAAAAAAAAAAAAQAAMAHAP7_MTwAAAYAAABgAAAAAAAAAAAAAAAAADACQhRfuLWrOB-kQZe7iu9uS_-BIQ6O5EoDZXUxUgBaAA
        expiresAt: '2022-09-24T12:19:11.465Z'
    personalAccessKey: >-
      CiRldTEtN2FjMi04ZjQ3LTQ0NjAtYjk2MS1iYzE1ZTdjNGNmYTYQgOSVDBjM7MINKhkABeaRgnT2uVni73e5gFnF2Cz9PMMRmA51SgNldTE
