defaultPortal: CodeSevenic
portals:
  - name: CodeSevenic
    portalId: 25522688
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CJ-TiPq2MBIJAA0AAAAA4A0DGIDklQwgzOzCDSju6QwyFAOzlzS4NnKfMFgTwX7iyTVO8w57OjcAAARBAAAAeAAAAAAAAAAAAAAAAAAAAAQAAMAHAP7_MTwAAAYAAABgAAAAAAAAAAAAAAAAADACQhRUP_lqIg_5xNr61j-56Y2ctyHC00oDZXUxUgBaAA
        expiresAt: '2022-09-24T11:29:02.372Z'
    personalAccessKey: >-
      CiRldTEtN2FjMi04ZjQ3LTQ0NjAtYjk2MS1iYzE1ZTdjNGNmYTYQgOSVDBjM7MINKhkABeaRgnT2uVni73e5gFnF2Cz9PMMRmA51SgNldTE
