defaultPortal: CodeSevenic
portals:
  - name: CodeSevenic
    portalId: 25522688
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CIjhqvi2MBIJAA0AAAAA4A0DGIDklQwgzOzCDSju6QwyFMPA1xPRezrfhBkhCgZMw5jcZ_vnOjcAAARBAAAAeAAAAAAAAAAAAAAAAAAAAAQAAMAHAP7_MTwAAAYAAABgAAAAAAAAAAAAAAAAADACQhTxtMissGnMA0efG-iJv0qnvUctv0oDZXUxUgBaAA
        expiresAt: '2022-09-24T10:28:35.083Z'
    personalAccessKey: >-
      CiRldTEtN2FjMi04ZjQ3LTQ0NjAtYjk2MS1iYzE1ZTdjNGNmYTYQgOSVDBjM7MINKhkABeaRgnT2uVni73e5gFnF2Cz9PMMRmA51SgNldTE
