defaultPortal: CodeSevenic
portals:
  - name: CodeSevenic
    portalId: 25522688
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CLrrvPm2MBIJAA0AAAAA4A0DGIDklQwgzOzCDSju6QwyFOLA_G5IFXz2eaEWZ4yw9_S1vq3gOjcAAARBAAAAeAAAAAAAAAAAAAAAAAAAAAQAAMAHAP7_MTwAAAYAAABgAAAAAAAAAAAAAAAAADACQhTIp8vwPWrc5CM_3EU8OLYJfy5FJUoDZXUxUgBaAA
        expiresAt: '2022-09-24T11:08:28.478Z'
    personalAccessKey: >-
      CiRldTEtN2FjMi04ZjQ3LTQ0NjAtYjk2MS1iYzE1ZTdjNGNmYTYQgOSVDBjM7MINKhkABeaRgnT2uVni73e5gFnF2Cz9PMMRmA51SgNldTE
